loop waiting for config

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -10,7 +10,14 @@ function server {
 
   case "${1:-}" in
     default)
-      exec linkerd "/config/linkerd/linkerd.yaml"
+      local pth_config="/config/linkerd/linkerd.yaml"
+
+      if [[ -f "$pth_config" ]]; then
+        exec linkerd "$pth_config"
+      else
+        echo "ERROR: missing $pth_config" 1>&2
+        sleep 10
+      fi
       ;;
     *)
       echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
