refactoring how script/server should run

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -4,8 +4,19 @@ function server {
   local shome="${_linkerd_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
   source "$shome/script/profile"
 
-  cd "$shome/vendor/linkerd"
-  exec linkerd "config/linkerd.yaml"
+  if [[ "$#" == 0 ]]; then
+    set -- default
+  fi
+
+  case "${1:-}" in
+    default)
+      exec linkerd "$shome/config/linkerd.yaml"
+      ;;
+    *)
+      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
+      return 1
+      ;;
+  esac
 }
 
 server "$@"
